services:
  kafka:
    image: bitnami/kafka:3.7.0
    ports:
      - 9092:9092
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: CLIENT://:9092,CONTROLLER://localhost:9093,BROKER://localhost:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka:9092,BROKER://localhost:9094
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@localhost:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CLIENT_USERS: user
      KAFKA_CLIENT_PASSWORDS: password
      KAFKA_CLIENT_LISTENER_NAME: CLIENT
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT,CLIENT:SASL_SSL
      KAFKA_KRAFT_CLUSTER_ID: 1
      KAFKA_CERTIFICATE_PASSWORD: hogehoge
    volumes:
      - ./deploy/certs:/opt/bitnami/kafka/config/certs
    healthcheck:
      # kafka image does not contain nc/netstat/ss. :2385(hex) is equal to :9092(decimal)
      test: ["CMD", "grep", ":2384", "/proc/net/tcp"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    pull_policy: build
    build:
      context: .
    command: ./sample-app-golang -config test
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      APP_KAFKA_PASSWORD: password
    ports:
      - "8080:8080"
