openapi: 3.0.0
info:
  title: sample-app-golang
  version: 1.0.0
paths:
  /hello:
    get:
      summary: just return hello
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          $ref: '#/components/responses/SystemError'
  /sort:
    get:
      summary: generate a list of random numbers and sort them
      parameters:
        - name: size
          in: query
          description: size of the list
          required: true
          schema:
            type: integer

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          $ref: '#/components/responses/SystemError'
  /kafka/publish:
    post:
      summary: post a message to kafka
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
                  description: message to publish
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          $ref: '#/components/responses/SystemError'
components:
  responses:
    SystemError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: 'Internal server error occurred'
