name: Review


on:
  push:
    branches: ["tool-cache"]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  misspell:
    name: misspell
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-misspell@v1
        with:
          level: warning
          reporter: github-pr-review
  shellcheck:
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-shellcheck@v1
        with:
          level: error
          reporter: github-pr-review
  yamllint:
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-yamllint@v1
        with:
          level: error
          reporter: github-pr-review
  hadolint:
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-hadolint@v1
        with:
          level: error
          reporter: github-pr-review
  markdown:
    name: markdown
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-markdownlint@v0
        with:
          level: error
          reporter: github-pr-review
  archive:
    name: archive
    steps:
      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          tar -czf tool_cache.tar.gz *
      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{runner.tool_cache}}/tool_cache.tar.gz
